steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mtk-booking', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'mtk-booking', '--image', 'gcr.io/$PROJECT_ID/mtk-booking', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
  - 'gcr.io/$PROJECT_ID/mtk-booking'
options:
  logging: CLOUD_LOGGING_ONLY
